title: 工具使用
path: /view/tool/
collapsable: false
children:
  - title: Git使用
    path: /view/tool/git/
    collapsable: true
    children:
      - title: 使用git rebase合并多次commit
        path: /view/tool/git/使用git rebase合并多次commit.md